import type { Model } from "@mariozechner/pi-ai";

export const CUSTOM_MODELS: Record<string, Model<any>[]> = {
  "测试服务（记录轨迹）": [
    {
      id: "ark/ep-20260127123225-bkrb2",
      name: "Seed 2.0",
      provider: "doubao-test-log",
      api: "anthropic-messages",
      baseUrl: "https://sd5so4ri31qkst0kfojig.apigateway-ap-southeast-1.volceapi.com",
      contextWindow: 64000,
      maxTokens: 8000,
      input: ["text","image"],
      reasoning: false,
      cost: {
        input: 0.55,
        output: 2.19,
        cacheRead: 0.14,
        cacheWrite: 0.55,
      },
    },
    {
      id: "anonymous/orange",
      name: "Kimi K2.5",
      provider: "doubao-test-log",
      api: "anthropic-messages",
      baseUrl: "https://sd5so4ri31qkst0kfojig.apigateway-ap-southeast-1.volceapi.com",
      contextWindow: 64000,
      maxTokens: 8000,
      input: ["text","image"],
      reasoning: false,
      cost: {
        input: 0.55,
        output: 2.19,
        cacheRead: 0.14,
        cacheWrite: 0.55,
      },
    },
    {
      id: "anonymous/hegel",
      name: "Hegel",
      provider: "doubao-test-log",
      api: "anthropic-messages",
      baseUrl: "https://sd5so4ri31qkst0kfojig.apigateway-ap-southeast-1.volceapi.com",
      contextWindow: 64000,
      maxTokens: 8000,
      input: ["text","image"],
      reasoning: false,
      cost: {
        input: 0.55,
        output: 2.19,
        cacheRead: 0.14,
        cacheWrite: 0.55,
      },
    },
    // {
    //   id: "anonymous/hegel_online",
    //   name: "Hegel（联网）",
    //   provider: "doubao-test-log",
    //   api: "anthropic-messages",
    //   baseUrl: "https://sd5so4ri31qkst0kfojig.apigateway-ap-southeast-1.volceapi.com",
    //   contextWindow: 64000,
    //   maxTokens: 8000,
    //   input: ["text","image"],
    //   reasoning: false,
    //   cost: {
    //     input: 0.55,
    //     output: 2.19,
    //     cacheRead: 0.14,
    //     cacheWrite: 0.55,
    //   },
    // },
    {
      id: "ark/glm-4-7-251222",
      name: "GLM 4.7",
      provider: "doubao-test-log",
      api: "anthropic-messages",
      baseUrl: "https://sd5so4ri31qkst0kfojig.apigateway-ap-southeast-1.volceapi.com",
      contextWindow: 64000,
      maxTokens: 8000,
      input: ["text","image"],
      reasoning: false,
      cost: {
        input: 0.55,
        output: 2.19,
        cacheRead: 0.14,
        cacheWrite: 0.55,
      },
    },
    {
      id: "anonymous/potato",
      name: "Potato",
      provider: "doubao-test-log",
      api: "anthropic-messages",
      baseUrl: "https://sd5so4ri31qkst0kfojig.apigateway-ap-southeast-1.volceapi.com",
      contextWindow: 64000,
      maxTokens: 8000,
      input: ["text","image"],
      reasoning: false,
      cost: {
        input: 0.55,
        output: 2.19,
        cacheRead: 0.14,
        cacheWrite: 0.55,
      },
    },
  ],
  "火山引擎（不记录轨迹）": [
  {
    id: "doubao-seed-1-8-251215",
    name: "Seed 1.8",
    provider: "volcengine-ark",
    api: "anthropic-messages",
    baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    contextWindow: 64000,
    maxTokens: 8000,
    input: ["text","image"],
    reasoning: false,
    cost: {
      input: 0.55,
      output: 2.19,
      cacheRead: 0.14,
      cacheWrite: 0.55,
    },
  },
  {
    id: "doubao-seed-2-0-pro-preview-260115",
    name: "Seed 2.0",
    provider: "volcengine-ark",
    api: "anthropic-messages",
    baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    contextWindow: 64000,
    maxTokens: 8000,
    input: ["text","image"],
    reasoning: false,
    cost: {
      input: 0.55,
      output: 2.19,
      cacheRead: 0.14,
      cacheWrite: 0.55,
    },
  }
]
};
